---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: radarr-secret
spec:
  encryptedData:
    RADARR__AUTH__APIKEY: AgBj7q5fkEh5cvjZiBIFO/b1ozVM+3eWlFrMr4+myXrkd+pwvF3DthulPxQubYUWGRR/6w1ySsbJqsh7RPCv9fcTAo5fWbKBRXnAlsIO5cCgaZwNDTXKL/778G2ps8J/kSo4YGFrQWc0Q0l/UYuR1ZOM9J6mWEc2/wrj+ko9VSw96py7clX9PNwmqEoRoTjo7jGfjN8YZy5CWO0MEnvnaW64SRXGERLBBFbS5iqRiHiNpZNG8AQq0gtblzbWOSseArk8nXHs/S13LTysUKe2wNN/U693LSKVTRZQlynLqQBHOms/bTB7bz83zqvHcaD1S5Itc8UjfzY8ssuwPx0r3La6fTmiJZkflUpgAUdf1J825CEiMMuenYJItRd0YVL2+P5FucXQHGSCwSTJWZDNsTx/EZaHPNCxFOtIZJoEIKXKGNhzbfPFl/il9XAJrm/i4NbUVebxC48WnuaJch5558xS6v58KZyR6CFXlwAEanUN2T0LkFncDvFJN0feUVYctyCXsxrGyJfGQriBdQWiilPR0M4CACTEsJf8ilp6ZdbNrjLvVn2k007orpxnafCNjBVhRP0lrwzhSkMDuFHKiB8wcMqnelf2BmgKK9i/bPkTQPvbkz2x+LmMpHC4ZG6ELGRfjQzUobZjYgvw1Ris2W6OOPULTG1KNueV94hapFtQDRzaw+aHk0ZfTQjiltouzvDLUi8RGpN2V9T8BQyH6TGeqcpawXm4rccAfGyCopUvcg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: radarr-secret
