---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: openwebui-secret
spec:
  encryptedData:
    lldap_password: AgB9Po7FQ9KJAKHEcJ7iOtCwrY9LaspNUlkghjRglNYc0HE3HhXOSJwDGCFHJ0Typiwxo24GcdRj6qp7c5eLva5jQk4aOwreAXF9I/OQ8isM64sKpbzkPNRxjqg8SyDelLaedqOwofVyngyvJxQnc63YsODGyfwUovWvEd0MtgB47TBXjnZOuOFGjj02+fOB/pnKnGsudSFtwZD3PJlraB8i9JyS9C8hbj1AveczY7Rf1duepDHFgJ0gecqIPfRBA82AOGn+CEb1QToxauzL5kZ/rMFm2az5SpQB+CESkcVVJdbH40H1EOFq/1V5DuzkNouyNrHvRdkot4t0jss8IXJJi5DdDNz52p8+WrCTZeEU60f9F9C3Frwl6nXe40qgZspWeUdbfPUFEqEypyu1SjrhvQsEuW0IKZ/w4yKoMCMEN408s69VB33+G+DUsrqoUiaQemNFTeICKp8UjcFYV+1od5KQKiXbHX+VQoxPZbGM3/SV6glyNQq9c4MMd5oltP8scOhC8b+Zt9yd+BmiHnWDH9UZ+QtgUM8RmRZ8jqVK/j+O25f8YjxXpvlQa1xec8UENnjqdiTuODHAbnehhUjtmiG+pV6hQqBOsjyRjRbVFu+LI+sqIfg0PkkUOQ0jSQrNTTEM1zoKKi5GwQfaY4weqZwIRvJQZEu7oq4gyBq4jNC97rBGhWOxx5p+UCQ1O42XPox7OUp9TA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: openwebui-secret
