{{- define "pilibchart.deployment" -}}
{{- $fullName := include "helper.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helper.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- include "pilibchart.volumes" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if (.Values.workingDir) }}
          workingDir: {{ .Values.workingDir }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.env }}
          env: {{- toYaml . | nindent 10 }}
          {{- end}}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
          {{- with .Values.service }}
          ports:
            {{- range .ports }}
              - name: {{ .name }}
                containerPort: {{ .port }}
                protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.probe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.probe | nindent 12 }}
          {{- end }}
          {{- include "pilibchart.volumeMounts" . | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tailscale }}
        {{- if .enabled }}
        - name: ts-sidecar
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:v1.48.2"
          env:
          - name: TS_EXTRA_ARGS
            value: "--hostname={{ $fullName }}"
          - name: TS_KUBE_SECRET
            value: "{{ .secretName }}"
          - name: TS_USERSPACE
            value: "false"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth-secret
                key: TS_AUTHKEY
                optional: true
          securityContext:
            privileged: true
            capabilities:
              add:
              - NET_ADMIN
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
{{- define "pilibchart.deployment.tpl" -}}
{{- include "pilibchart.util.merge" (append . "pilibchart.deployment") -}}
{{- end -}}
