{{- define "pilibchart.ingressudp" -}}
{{- if .Values.ingressUdp.enabled -}}
{{- $fullName := include "helper.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
spec:
  entryPoints:
  {{- range .Values.ingressUdp.entryPoints }}
  - {{ . }}
  {{- end }}
  routes:
  {{- range .Values.ingressUdp.routes }}
  - services:
    {{- range .ports }}
    - name: {{ $fullName }}
      port: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
