{{- define "pilibchart.tailscaleSidecarRole" -}}
{{- $fullName := include "helper.fullname" . -}}
{{- with .Values.tailscale }}
{{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-tailscale
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  # Create can not be restricted to a resource name.
  verbs: ["create"]
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["{{ .secretName }}"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
{{- end }}
{{- end }}
{{- end }}
