{{- define "pilibchart.tailscaleRolebinding" -}}
{{- $fullName := include "helper.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}-tailscale
subjects:
- kind: ServiceAccount
  name: {{ include "helper.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ $fullName }}-tailscale
  apiGroup: rbac.authorization.k8s.io
{{- end }}
