# yaml-language-server: $schema=https://raw.githubusercontent.com/vidispine/hull/refs/heads/main/hull/values.schema.json

hull:
  config:
    general:
      rbac: false

  objects:
    serviceaccount:
      default:
        enabled: false

    customresource:
      forgejo-ssh:
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        spec:
          entryPoints:
            - forgejossh
          routes:
            - match: HostSNI(`*`)
              services:
                - name: forgejo-ssh
                  port: 22
