hull:
  config:
    specific:
      httpPort: 8384
      natTraversalPort: 22000
      relayPort: 21027
      ingressHost: syncthing.joeldollarhide.com

  objects:
    configmap:
      app:
        data:
          PUID:
            inline: "1000"
          PGID:
            inline: "1000"

    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            syncthing-pvc-jdollar-obsidian:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: syncthing-pvc-jdollar-obsidian
            syncthing-pvc-config:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: syncthing-pvc-config
          containers:
            app:
              image:
                repository: syncthing/syncthing
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
                syncthingtcp:
                  containerPort: _HT*hull.config.specific.natTraversalPort
                  protocol: TCP
                syncthingudp:
                  containerPort: _HT*hull.config.specific.natTraversalPort
                  protocol: UDP
                syncthingudp2:
                  containerPort: _HT*hull.config.specific.relayPort
                  protocol: UDP
              volumeMounts:
                syncthing-pvc-jdollar-obsidian:
                  name: syncthing-pvc-jdollar-obsidian
                  mountPath: /var/syncthing
                syncthing-pvc-config:
                  name: syncthing-pvc-config
                  mountPath: /var/syncthing/config
              envFrom:
                app:
                  configMapRef:
                    name: app
                    optional: false
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 50m
                  memory: 128Mi

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
            protocol: TCP
          syncthingtcp:
            port: _HT*hull.config.specific.natTraversalPort
            targetPort: syncthingtcp
            protocol: TCP
          syncthingudp:
            port: _HT*hull.config.specific.natTraversalPort
            targetPort: syncthingudp
            protocol: UDP
          syncthingudp2:
            port: _HT*hull.config.specific.relayPort
            targetPort: syncthingudp2
            protocol: UDP

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Syncthing"
          gethomepage.dev/description: "Syncthing sync service"
          gethomepage.dev/group: "Applications"
          gethomepage.dev/icon: "syncthing"
          gethomepage.dev/weight: "1"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    customresource:
      app:
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteUDP
        spec:
          entryPoints:
            - syncthingudp
            - syncthingudp2
          routes:
            - services:
                - name: _HT^app
                  port: _HT*hull.config.specific.natTraversalPort
                - name: _HT^app
                  port: _HT*hull.config.specific.relayPort

      app-tcp:
        apiVersion: traefik.io/v1alpha1
        kind: IngressRouteTCP
        spec:
          entryPoints:
            - syncthingtcp
          routes:
            - match: HostSNI(`*`)
              services:
                - name: _HT^app
                  port: _HT*hull.config.specific.natTraversalPort

    persistentvolumeclaim:
      syncthing-pvc-jdollar-obsidian:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 10Gi
      syncthing-pvc-config:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 256Mi

