# yaml-language-server: $schema=https://raw.githubusercontent.com/vidispine/hull/refs/heads/main/hull/values.schema.json

hull:
  config:
    general:
      rbac: false

  objects:
    serviceaccount:
      default:
        enabled: false

    customresource:
      tandoor: &defaultDB
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        namespaceOverride: tandoor
        spec:
          instances: 1

          monitoring:
            enablePodMonitor: true

          managed:
            services:
              disabledDefaultServices: ["ro", "r"]

          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 100m
              memory: 1Gi

          storage:
            storageClass: nfs
            size: 5Gi

      forgejo:
        <<: *defaultDB
        namespaceOverride: forgejo

      synapse:
        <<: *defaultDB
        namespaceOverride: synapse

      nextcloud:
        <<: *defaultDB
        namespaceOverride: nextcloud

      umami:
        <<: *defaultDB
        namespaceOverride: umami

      calcom:
        <<: *defaultDB
        namespaceOverride: calcom
