---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgCpbJddQOmcNHdg7Y0sMBhlkcdTM3Hog0OpM9KMmA+DXiqbNMnjZmHW/zF7q90g5qMZTb/j19aCFGsclFeyv1QNKKTRPRGzHgVwAEZXJS4nKijNTbbJLK7RfnSBqCuwNKZrzMiak/PGhaHAQ+Yz8yPtzvKnLMn4UkaakyCvEvBKwImkriupAR2Lo0fg6OGHlrvZ31OKfgN4D8l6CgQ9diaeHnGoDL9VRRei7aC/gX13mY17IU+d7rUZhnKxLD/b8nZBsEbLgxHYmjmwavjaNo5xmbKCyWSJhw12jP2S7gJf+5ucGwnPbd+PDFu+0I3Z3ZH/l0ODQKLibvwMdgMkz8LpMTaDd2W8whTKppNp4dCmIJhhgQV8CkHT6FhRtar/mRVTcmAoK+7x1URb27Qc9d+riKxE+KshlMXfzZwfR/1xindln2EJRpDEOJ0OjitjUWKiBA3D0k5MH9P/wdnUnNjocL7CaSUXu5PuPcUPK2pgeCKe1x8xiHxMQavHuHNv6uc0VeHEVbyEy73CLbhLiVXxx6dsehC/gJKYq28FAPwXHXOtG2tk7E88yHMp4ZRZ0zLxBDuUiqao0+pB685FvIyliFn2EVUfYvg7lNy9qQgfEViCoIw+vnRx784Y3TY81pWl/KOwQc7qQjI6T1RfV1hWKHCxXo/b1HfY+4g2+dFeaH8Wx0RputbApQLxowElvcAxiRKTAkS0UEKxjA2xPl0lvZttMl2kmh8UZHZLC8BeYXF6NenxqT1r
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
