---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgBBlWj4FJQhQXCMXdEqhXZ1bq1S89MsgEwQqyhmIHjEZ4bxaWys24yyE2DbpVNKGAm4GtwNFbmJezQj7YLmfVFy4AheDSrHcrWMLrqv1Tw1hcj90rx7Y3kfeMP469gMYDXWcwIjcHFaUUhHbqGLuML49qJcb2cJ0PKA4pP/3MmHg5NdwyO+jIYBORwgq0Gb/woaH8cemjx3Ws1QuMIfZeXwUvMZtG4reTl/uMB/fxykkTlO+Vu578dBr5cfPTSvYLAQBRrBtRFD62RgDLfJGCIcSgZekCQbMx3g2hRq2/KAss53+BVqYXQ2h9c7iVA3/qY80a/ct6EUO0ljLoyCiUh56Ttut3nJIZvN5MZrQdPZlPmCQI3mYKKyUqXxsro9uwZfC0cACcMoqVsSPO0krxSNR6gFWC6lJ+ojQWr30JChD9IOn12oJ9iL+/+MsCcStnCCtkwdNVfwcIG4dmpL0viRNyuEInndR5nO9wYOHS9sj7TrElWP7Jl1X27CG9e/+e7d/0VndhVRoGwKLvX6r2uVSWtbaNvJsP0HWHzQ+BN17vp/qXLLYnGWQAqTq+ttg0Ea1NuSJdxVdSOr7fZ+LQR2H6eR2savKNvI3oXZlS+VjnO8zP5+71S3qVlYqOmkSCEunfrwFEuKMFZIHKCxaVNxgPJxIan2IQ/t0KH7veb7O3RkGLckY6+43V8xypD7eKdc7Pr2Yo+200LWj++nka9IWpl1Z25QDSB18EAPNvRH+s2FkixT/1tk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
