---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgAaCPzWWBvkUkfEqQCSYKIxvGQdK9/Q/jHRAn0UwOmr3j/MGmAO5HYOLn4G0yNCXTYfuSrJDcSwWK6m9rQlJOCohqmhavwgeTjYapZoBMrvalle5x8erfKX0VN4qQdxUUYwl8AP0IPG+9zJx+/u85z2CGGaT2DSqg5B1GRIMKvIOpCvxxkpS5+TWnhtFUmkYUSV2t/1WRidt3pQKNyYCKNcuO90JOv9PT+Uv+v5SrfcrcHooCTE1cqI7hzO1UfESvDjCEw5uBsfouxWfPx1xgPQISpFVN1VhVL56hHWCTw7F5m6YCBoPlSrjoB2oVQgU1tivljNygYpGypGjC7CJPSjghd+MUj52myUFDR51ik2WJHTcgKxahKKR5vsY/LQ/+IPHeuSPAQe2mLxZt/P2vSo3KIearTq8V2dymnl/DrEXbcDp2IURnQ6sSlm0TFnJNQ3upKHVmbGGBL7xYlhg6CB4NilbhcQzlbSi/y0qYNEIijULoV5PRCEKP1tYLVsDhRRLQ4HJj6DShK1DQ7wUbVv4RkBmny5feK6RkbrD9aEM1FDMby2xJYCL4HDwClY9UbToRlBOZKB3P9+GwNrvm/tvEyxtdLgU6wN/WFT7M42GmiZ57PNuTP7d5AH87YBrtJRlhfdtHbLREkx/mxcPmESL7uakMC42cNATLJjRQlAvnYtEz1e8LBWtg6gfSighC74QTs52Dl2Sze/V6IjHQ959EzYdyLiPCtZzxousF+qobU2yc1x87tJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
