apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgCiwtsNBoR/2sNqKpngpAZsx6SXMOz9EaMLIapMl3bt7BO15rPQrstTh/7+/7Dwf6BpYYbrbha7BPGaWuXRjvqM15BepR0uXOsV0jlL/Lc91vQD55zOWb4REsbtTN31DoIxXDKXirzN5N+pHmqpGmCAlNIFiOkTogz0xAeNYCJ851r4j8313mFkQ1p2jloUhja/mvrXFHRsqZlOVHN8p/w5qK6Z/PO6CwnAWhAgS8e3/dCoBaRBOqYDSGPTp4vVZ2ZXJvBiY98ihDdita7FR2uIq/ua0M06+rwjFSpYUOQLCdedV6x0qXw2pcxUrvb/jesX8Np/fmMfHdyAdDehMnuHaf5p2ZsynTueZZCZGQ23lsrWo10OXUn2qKF0COeNdtmEZc0/qveReXgYr+5T9f+8xnVmgpIFxak9RyI+pvuktyPmabj98nacFtRHqi+LBmGRcZujk5RxPKUzITlpfyimS8VRAudUgkyiuVrYg+NFzQ5lWJGz295QQUNm300dnfl+UYLOLxt263BcJcOQEJx+GsonI1QYke9s2ABPNZXaUTimPR4cnN+Fceg1A4HY3hRTVm2q3SKOTjG1yBpZcx//gszn9IeEq2TUrI2exnEl5I6vlS4pmYWiSFZWnC9B9pXXFc29luF1I87TTc6G1T6dNKfEY0ZmlgPjztsfzZCDjqN3YGIg68XKEo3AXMDgS3tlJtKp/Hl6F1DKdKXzDNytBi0RIzQGNoF4tdKnymE2Q8o4QvRIfbDD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret

