---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  chart: actions-runner-controller
  repo: https://actions-runner-controller.github.io/actions-runner-controller
  targetNamespace: actions-runner-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgCIyTxHOYRP7SeCQj+JRT98vmwSFzG+7yTKYcpqYCNVkqIKEhE62sHzCeRcmVOeDYn53fXcdESwHENymKJllNeCE/ZTKwVNJrT1emLJQ0SGDq93VrZ/3opAwbLYOlj/D1v1eDIInIozg2mfAz3txNSZT0S55p+LGeyaHXJe6Mz0M1HVDs+AolXsZaZAXb+ehWtKu4y4VXBNaM5qG9aWkHW8LvzIpIUoXiAvq4N+WbFMG1LMDvhpf2zXRTZXGpayzKa90fH6/q1q8BNWpCOaApSsJr8iLvSH26Ab1ICFwJ1YFyjQyVUK62bJ7Bk2WkG1H2EhENSPEKQj5YrMhWEDQbJzTyDeUTn75lhkh8yh4SPalH/ewgxGUHFqZdes5fC9kgkAEi9TLaljWifDi/H1z5jVVDHvFDfjDzGRintV8ccMeg4arMSP9X8qmBHeWSfLJ0dJ7N+jFH/gfLTclaablxy8pVYk0A1/OKu+7A3mtdfdV13UN3YdTix1pNAoRLw6CIR4nmyMykg16+wBTBdAxtDj2yKqwzTHrJn/5ix8Szfj1V/017HwAkGp4Jacr4HrNRWa2hf8e64k9d8i/fbQf6WU8+KDadsNDktqq7mHGdi+M8Mzv2Jfw00lM8IS+Q8VIiU/8qZrgez5QptTqwC8WRLW6cePLk1arTbeou5EYv44SkzIFISUqNwF05D6tB9LCzelnldw43gw62gWHPAkw4905GIzD2T35V32XJsTDA0r1BbiEhxR9jJX
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "extensions"] # "" indicates the core API group
  resources: ["deployments", "services", "configmaps", "secrets", "ingresses", "pods", "pods/exec"]
  verbs: ["create", "get", "watch", "list", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner
subjects:
  - kind: ServiceAccount
    name: actions-runner
    namespace: default
roleRef:
  kind: ClusterRole
  name: actions-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: homelab
spec:
  # This will deploy 2 runners now
  replicas: 1
  template:
    spec:
      serviceAccountName: actions-runner
      repository: jdollar/homelab
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: personal-site
spec:
  # This will deploy 2 runners now
  replicas: 1
  template:
    spec:
      serviceAccountName: actions-runner
      repository: jdollar/personal-site
