---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: csi-nfs
  namespace: default
spec:
  chart: csi-driver-nfs
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  targetNamespace: default
  valuesContent: |-
    storageClasses:
      - name: nfs-delete
        parameters:
          server: 10.0.0.65
          share: /volume1/cluster
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        mountOptions:
          - nfsvers=4.1
      - name: nfs
        parameters:
          server: 10.0.0.65
          share: /volume1/cluster
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        mountOptions:
          - nfsvers=4.1
