---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: registry-credentials
spec:
  encryptedData:
    .dockerconfigjson: AgAvCwRgugYbAVONUpnSaD420ycz/Ls3NStMeVVKyjwJm12uTEm9eAz+Jtg1yGWNktoB8h2T18mJNZPAGE6FeeSLBe0Ta3QGveVHIWqi7OV2PBNJJoGQlxM+kce0/4exbz5o6GSAp2jOZlRX5p6QDUnVd8TGF2aEoaA5h0kHgkOmRo+PNAnhCJ+qMAt94fFJ4rePkeOmIogMznB2m5iZ+sriZuZUcP17sIwOE7kxAvF0XmpqSbY5F7ZVTacoa78pmMkNHItZACH+JqoF2OVFT3rt92parjSH2Oel+6etRHCaYtoJTrbT38bIPuqaLuphGGCqriaKVUVno1B5gpW0cvzC4HxShbs4QWKicd44A07tuHVPXPFimtx3do7BGLBx3y4qC/yEy8YxLZUXWv8tYAF4P51vmfaCu9VZBaUN1QKUMQM6EbhzKkcaxDx/aBE3TqA60JSp1it8iUkeIN8ZcxwzGZNXY8BrG0cjsSLxkKw58CiDmI68GY26iGbeO5uHeIbD+n9O2TeA6BnG8ty3rUXxXVHDiBdCIHT4tuK7TzOK3E6lm43XrOZTjrW1rLMKdkK32IQvJ77so7DlejVreckTddartyjYuYzCGDVkiOYfp3BxiwfC3kbWBRQaihi97ktO6uQglkoSdINEEC95AjQ/BnQqQomsQJN1HIsmExtddS12CXRg9wyjsp6CATWgyp8BbQvl07zsqn0WMVgjUI00kgZJZlaGwgj+wen4nFsepNgH6qMGm1b4PDn2ji7Y3tSJaNnQvQHHGgWEd9Ce/8L45JJsDTtpkjmog0jn5lR7bvl4rcWHVCbC+sVSgbPvwGLetHPMLVZAYnn4PQk9hWPkTc5NI9h4cxaGB5n+mYloB/i5G7Y1QRXp3pe0L10M+geARXZY1T3F8HSWzq5DRVYSRnsc5o0+/HrsOIXOpOH8TC7qk1pohsYQuXDgiNBL7aDTUf/EHSMPOIt6atTCLy4ifokLCXntx1hAHpxRd54S8JELnved7cM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      name: registry-credentials
    type: kubernetes.io/dockerconfigjson
