---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velero-minio-credentials
  namespace: velero
spec:
  encryptedData:
    aws: AgA++z+tDnq+XV25N6jD4eNpl5I0r+cyb+cM0/LG/lihTw3H1iiXC/2qPf7B9xnLqQIjK1AjeR5Hmq4dfdzGU24dFk/05LkfCxOUnuEeld+MQoUetzTV9eEuBcrtayLwJMHZ2FsA4P/tvFviuUxjnk2LWQ1wz/lH+UyhdpGYWbevKOCxvJNgsLRE5lzFWVl2HR7GfXfuRHw20Mt6lCnLoBnbwQM1oO2oJFq7W66eKEA1XZEk/8hZt/siqF4a6VtjWdwPdWw35YhkGfu0yMj+ovoF6a2WxqRUbyFUySmobhuNVhR272k9On4fgHfT8jVhNZD6RIibSjcPPnNmRwejNCFofl3/1skrkCrEZIP+kXPUKY2jf07P1mXlbfKCGsr9TvuMwTqikY9fJ+vS/cEy0r9pL7olEJJYa6QQmOB/irXM7WlCEB/0NLqQp6CzWusZLmhK112n8J1qe2VJ1mBocMB9URNfaEn26TKNY4QbiASUm2bQmuBJURFeeqsX7biCbubcC+FTuM1LRG2U0kWmRxIqd/6iOLFguOGRZc3g0uoyJX3kvNHb+dKiXfhjVs0LX58PqR5d8xpi0s7yDD8dPuMXXGhYaN2Oqc5SsJVWDcVvIxefFtKfC4V6lv1YUZbOhJjd6hIj0iBq3dyD89jxwVChFUCq3g/tiU6fGWSTYePZSaoeZUC5mh9vc/l0xBq03pizZTQRwEJHEk1SowHyFXQftRQS5xkfjhoVCMHLZusqw3Klc0TfzPSPq7EPTJtodzmsdZwnDlt42ZPeImbD5Wj5zwiHmOBwXAaC6xmoYfJ6X2smi75jc5hAsyG7m9q3mXJQm7ONVhLYheWppT2Ga4V4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: velero-minio-credentials
      namespace: velero
