---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: penpot-secret
spec:
  encryptedData:
    apiSecretKey: AgB9cbnhFcCVlUYGXvDVPAgp/ODBr/GCWie8OFWdbJ6mv7UahmX1iBYI7iKF7kqFEqM+9TfuPpC1q8HeOxkPMRvIKAlRCYJTjlBb3GP2W8c0Px00BWIKa0nNzHCY5A2Yk4iy1RVTwEvcIIOUvBIO6VSQInanLuFiDeUzsqwfGy1xCtFYuGfSKXYThSwwpus8kEI0OjyqqnimHB4yABvM3fmq7kPDl8Xx26pXnELH7q2YP3hTUmb3WpzSa7dQPrasduGRvsjIt4w161U6IWJKtERdmLn7+J+r5coCQvNyPxN26iyy5VE7tgZniAvRHDpW63l7Bz05ii08dXQyJF2HNj8EVAWLLV4lR+k09xYpVlZTob78fHCaC8FRm1AXryBQ+hg0Z9AEngiibDvQY0U99br1gz+IiV2DiFJIGnCyidJ7ykN52wgIYkpS1KUcLRAsmzeCkrrjOU3gDX0Zud61eoSV3260C2tkPJE1fMlM/6TXqWVB5O4Ws8jGt+2BEQB65otoTXe8qAFjCKWG6vjPvLWmXLqafDewpRZEso4uh3SniTarWb+bZ5XDUbpzfYA8l40b8mLVlZZc0SsPjSM+dyeXB6Hiqddix/lK9bjJLjNIUQVrQDxEdO1u9CpWn6LmKeqt6Yc3cK1+ElDyvo2Jk7ogjxQtjo76sfXJ0bZTtMBLFFvltW+JHi3aLfc0iU49UA8y0FC3XhUNftv1wJviHJQO5wyV576+KJswE0kYC3XIo56HypeQ/rSC5n88Ul0fVAS1GqRwDsEZjPohCYfSO9JxoUH77rE/QJB1SzGh+b/edR4L4VHFgQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: penpot-secret
