---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: authentik-secret
spec:
  encryptedData:
    secretkey: AgCgylAAOkcTaVq9fwGugS4TgQkQoz54fNnd0xmpWczWO9ZWlxxSaXHNprnPH0Pde8Ps3XRbYo34EIh1g2LQEUtQs69tQ5aq4W2Ztsx9ShXWB4txeV9jSBwrY7JlCj4DCfjFwnb+K794Y002ahNpi19g0FpUeSpb2AVFqUO+w7xbz6SQTuIlSikTVb78eiMfwCmm74Q9Adw0gfJhDOJAuQgDMEN4qNzez3/S3uanL14M7+DQpqaieQmLjJCpO6OSG1lsUeliUMVpP4mi4U3aeOYGOql8RfJxj6FG0z81Fx8hEyFaSS+wHfehbRxD/ongMjux4re7aagDOq2YQbzINQjJM9dWpxCHpym8rDlpbIIsSmN7s+GpM8GGXawKIQ8cMPxQGSnRFZ4WmtcPtx3DCSRgp+e/ZAQmA4Jun/iM9b6WkVkjceoKueIYXCmrt0pqu3coRIiE0juvjjkQpKCEKTyCSC+YzwdFTFE8DkRBpf6QWeJ/nXumuFCy0F0a3J7sBl3HoPZL8Y46JdYRyoYxB82Ks21mYzbTaz9vP1RYAD7jcihXXMFAtVMTqohsiD+KjSWwOIzbLXTbXTdhmhVJYSjaeL+DdO4YA8J+gzLIFyySDTAkK6dY3AEPwePWQvaNdBwjCtbRpuAebbZUbuTfKXrRcIaYZaf2vEaLFJ2H7XI9kROPkCK0gpMHiKTFMQ0RPPdRhQ/7IraQ5dxTtE4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: authentik-secret
