---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: woodpecker-secret
spec:
  encryptedData:
    WOODPECKER_FORGEJO_CLIENT: AgAEddPaJ9vYNC8zB2gJ9F0cmiCRakM+Vodncn36lPyk24Anjr7C3pknDWOpTwEH14jae83SqAShslCRQrmoaYNNHHpNarN3/2nllEZ3PNiTDlNrexRuPI7qQy0pX1BV/GMA/2JI3sgZSFoJeFTveHMAUO9boe1tckvwwUyYOuShibqP8DX0yUEmzpuooqwIcYKl2svutbk/iwP28gMpHFqoy7iwn54Fj91QNBJqFSZrGNnQTQjddM1j4YOIdQLBK5GE9lGa/o3esHbsIMYYb+XrX2xuLxTjQ6QHY6UUpz93whMa0YGHzlkw75kqJb1nIPXWNoV4M2AB5G3rnXJxDd4tzFUSCdg7a0s8VmeQSt8P9PuIeXm0ueMqLuL9ZRDnAuaw5qRMgT0FmS1YCi2+ErLYfm1V7IVaQILjvuXgkXb5lW3KLWbaJflZi0g5GZJpRLkAt6ZDOidtZWp7NcwcG0Yn4x1z4hSbZibsxH4pZ0/H64I/qjpIlCP8h0JWBW5h9y+udSUrPaijwfrB86kZ/6oDI0SHL5WKGKuXaScpWa35QD8CQ8/xDmP5wDwtSZRUnPCyLkZ4hu9Wg6fONPhl+K42TrBkXiCdKRL+aboU5wVTwZtdy6Ma+BF613faBwzEq2yY1UsKg3aQTZD0TSI3idC75mHjeKrnjIiGSEVZ8bk3I6jdYFlOgZLuQUBI/zKW02qo9gOWKmpmH/kQrw8DPp2iUvndQToMEBqj0yuygNnXSn+D+AY=
    WOODPECKER_FORGEJO_SECRET: AgApgE6jJ8nR+Z59Ko9i0ZzRTaVEWLotu8C4ht5tN0jsAUpjG85d53+yvg5RgRzOhoW8/LKvTV7SicdAfj3zCv6T6ZL73jmK7/SCEEEdtDDVzB8zcImU5nL0vEQyr4OfmHhIzH2AgecGDHuwvpuh6KK2GGPEe6k7x46x5hVrxx55/LMJJXy6v9ELp2SLRzi5YrYSqXLRmsPSo+5lYc8rZOVdWEhatpelyP/fHrpiop6FmKLOoq/hvBdaF6d+VY+om2ZHGrGUP5If/o2Mlb2tuXpQOnD9Za0aWhT8rFQjXGr3i2FCAb+3DoGmBkZNpm+kPrEPsn6KMpRyrfVJbtz9TArIu5Vz6WMVNFlITDLfuDo5RZpskLjjBJVE/dbj5iHAC5zHpPtCioyFrQFlBt+xPtpVYw4Ao+3L6hTwSFFtJ4vZohFf2FiZLHZ3nXfZxHx1L6uXjrupF5R7aFvJ6lvTXW/+Aq8Hr8HM2J9NG88d4C+n+bLEiFX9+Uu/wcUNb82tFHHE94EgEHEAtmtuDOjnqwKmIZGkp9xV3RGBm9wUXWHqo11iN4j120bs7BX9ypgXtRSmS0/ZocSAjGxZ33EpuUBkST+URXSYumBofpdK/yC11DqkHl4Qt7N9itHs4x0cicmIpLm4Jmu+Hu935XGk6AoNuNSo1+BOGsmtKbW15kOMkk3a6aAY2hUV9qCyqJ8oypRXGxhtKcYY7byxbLG306LEZr0uoZT+e3HqXOaq3oH4Cy2gX121FlEi/zbDfDzcm9/rjEVi3rxzTQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: woodpecker-secret
