hull:
  objects:
    customresource:
      app:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        spec:
          instances: 1

          monitoring:
            enablePodMonitor: true

          managed:
            services:
              disabledDefaultServices: ["ro", "r"]

          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 100m
              memory: 1Gi

          storage:
            storageClass: nfs
            size: 5Gi
