# yaml-language-server: $schema=https://raw.githubusercontent.com/vidispine/hull/refs/heads/main/hull/values.schema.json

hull:
  config:
    specific:
      httpPort: 80
      ingressHost: audiobookshelf.joeldollarhide.com

  objects:
    configmap:
      app:
        data: {}

    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            jellyfin-pvc-media:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: jellyfin-pvc-media
            audiobookshelf-pvc-config-longhorn:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: audiobookshelf-pvc-config-longhorn
            audiobookshelf-pvc-metadata:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: audiobookshelf-pvc-metadata
          containers:
            app:
              image:
                repository: advplyr/audiobookshelf
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
              volumeMounts:
                jellyfin-pvc-media:
                  name: jellyfin-pvc-media
                  mountPath: /data
                audiobookshelf-pvc-config-longhorn:
                  name: audiobookshelf-pvc-config-longhorn
                  mountPath: /config
                audiobookshelf-pvc-metadata:
                  name: audiobookshelf-pvc-metadata
                  mountPath: /metadata
              envFrom:
                app:
                  configMapRef:
                    name: app
                    optional: false
              resources:
                requests:
                  cpu: 200m
                  memory: 512Mi
                limits:
                  cpu: 200m
                  memory: 512Mi

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
            protocol: TCP

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Audiobookshelf"
          gethomepage.dev/description: "Audiobook streaming platform"
          gethomepage.dev/group: "Books"
          gethomepage.dev/icon: "audiobookshelf"
          gethomepage.dev/weight: "1"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    persistentvolumeclaim:
      audiobookshelf-pvc-config-longhorn:
        staticName: true
        labels:
          "recurring-job.longhorn.io/snapshot-cleanup": "enabled"
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
      audiobookshelf-pvc-metadata:
        staticName: true
        accessModes:
          - ReadWriteMany
        storageClassName: nfs
        resources:
          requests:
            storage: 5Gi
