---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velocity-secret
spec:
  encryptedData:
    forwarding.secret: AgAh1EEwJjYZ2oMc+88Cuuyom/zRW+RHWKnkoAXm5WhuASaffiOUtIdD+iJQFhF0hxqpFgzkFOOtLpvjgO5ln/lxDdQO055wMCIYWm5yR6o5ySHFADtVZ6xNzQ25Phd/hHBEsO47G3LZ/BCOl1f0BzvJWdFwQaemuZr3fLe5a4YJbrs9/Ae6HlZn6TJB9wqxkh4Rh89s5lyySJoJpiBUNdbdWdRQpP31pMnQQnBEnYk/DoP5fJ70scVYDv1Z+HmelyB/ScVNJd1cw9RZJg07xHx2RpYeh86XmjyvUA+ahegw1p8IFK7rAijRke1H8WzzbOIClJBE04AJmAY6i0+gwf3nbYwvO7BJVWtaDUMimqanGEaXZ/vgEZu8mBLT6n75UyPWsOstGL1J8j4HSdO0ui142d0wAETE92SuSIJEzTMKfAF9i+hu5ed96qiTVuREumbTpnf8umwBP3Sx0JAswVHQN97KxoMDELiGpDdimh5EWcWXrkY6THxKy+8H88BjgOmPGRStaFq6QJc3FaSRD8RTysq5ypYfKdBkgQw4g1hQXuVkBS06WK59Jv0/MkhhYBrxB6Cn1PD6zWkKXIAOEy14JcEP4E2X7rJAPa5C/p2s13ZTZMZd/RpR11LLCGl6FPzGoGVF+rXxTCnpoR+d8Xxp9/A/QfAC3yOf+WDrRms0apy9tC+H9YQduleOre4xP8iPmyREmOU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: velocity-secret
