# yaml-language-server: $schema=https://raw.githubusercontent.com/vidispine/hull/refs/heads/main/hull/values.schema.json

hull:
  config:
    specific:
      httpPort: 5000
      oldIngressHost: &oldIngressHost booklore.joeldollarhide.com
      ingressHost: &ingressHost kavita.joeldollarhide.com

  objects:
    configmap:
      app:
        data:
          TZ:
            inline: "America/New_York"

    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            kavita-pvc-config:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: kavita-pvc-config
            booklore-pvc-books:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: booklore-pvc-books
          containers:
            app:
              image:
                repository: ghcr.io/kareadita/kavita
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
              volumeMounts:
                kavita-pvc-config:
                  name: kavita-pvc-config
                  mountPath: /kavita/config
                booklore-pvc-books:
                  name: booklore-pvc-books
                  mountPath: /books
              envFrom:
                app:
                  configMapRef:
                    name: app
                    optional: false

    service:
      app:
        type: ClusterIP
        selector:
          _HT&app
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
            protocol: TCP

    customresource:
      redirect-booklore:
        apiVersion: traefik.io/v1alpha1
        kind: Middleware
        spec:
          redirectRegex:
            regex: ^https?://booklore(.*)
            replacement: https://kavita${1}
            permanent: true

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,booklore-kavita-kavita-redirect-booklore@kubernetescrd
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Kavita"
          gethomepage.dev/type: "kavita"
          gethomepage.dev/description: "Selfhosted Book Hosting service"
          gethomepage.dev/group: "Books"
          gethomepage.dev/icon: "kavita.png"
          gethomepage.dev/weight: "0"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
          old-app:
            host: _HT*hull.config.specific.oldIngressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.oldIngressHost }},
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    persistentvolumeclaim:
      kavita-pvc-config:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 5Gi
      booklore-pvc-books:
        staticName: true
        accessModes:
          - ReadWriteMany
        storageClassName: nfs
        resources:
          requests:
            storage: 5Gi
