hull:
  config:
    specific:
      httpPort: 3001
      ingressHost: uptimekuma.joeldollarhide.com

  objects:
    configmap:
      app:
        data:
          UPTIME_KUMA_DB_TYPE:
            inline: mariadb
          UPTIME_KUMA_DB_HOSTNAME:
            inline: "uptime-kuma-uptime-kuma-db-internal.uptime-kuma.svc.cluster.local"
          UPTIME_KUMA_DB_NAME:
            inline: uptimekuma
          UPTIME_KUMA_DB_USERNAME:
            inline: uptimekuma

    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            uptime-kuma-pvc-data-longhorn:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: uptime-kuma-pvc-data-longhorn
          containers:
            app:
              image:
                repository: louislam/uptime-kuma
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
              volumeMounts:
                uptime-kuma-pvc-data-longhorn:
                  name: uptime-kuma-pvc-data-longhorn
                  mountPath: /app/data
              envFrom:
                app:
                  configMapRef:
                    name: app
                    optional: false
              env:
                UPTIME_KUMA_DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      staticName: true
                      name: uptimekuma-db-secret
                      key: password
                      optional: false

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
            protocol: TCP

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Uptime kuma"
          gethomepage.dev/type: "uptime-kuma"
          gethomepage.dev/description: "Monitoring"
          gethomepage.dev/group: "Application"
          gethomepage.dev/icon: "uptimekuma.png"
          gethomepage.dev/weight: "1"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    customresource:
      db:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        spec:
          username: uptimekuma
          passwordSecretKeyRef:
            name: uptimekuma-db-secret
            key: password
            generate: true
          database: uptimekuma

          port: 3306

          storage:
            size: 1Gi
            storageClassName: nfs

          myCnf: |
            [mariadb]
            bind-address=*
            default_storage_engine=InnoDB
            binlog_format=row
            innodb_autoinc_lock_mode=2
            innodb_buffer_pool_size=1600M
            max_allowed_packet=256M

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 1Gi

          metrics:
            enabled: true

          tls:
            enabled: false

    persistentvolumeclaim:
      uptime-kuma-pvc-data-longhorn:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
