---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jellystat-secret
spec:
  encryptedData:
    jwtsecret: AgBBdrBuh5oHbW5kp08xKxYWnVahTj+LSxKfrsgkA5gIWphtiapG9pdNFqveLkWXxDQd7v1+wCgVBpuj9ySqo9jApcGC8OV2uBL2N4bFCr8hROShz4cfMKygQJ7QNzL9oVJ9BaxutHW1OMvKecEsPciKDEwKvBb4AHxpmfqWvWcWzIQw8ZEeJUOO/adxCaGJ7XJKSVlfW2UkeLmS/NZfPKugcMIQCl/5Oo/2YowOA7FllcRrrHZkICc5liTKggYyNv8CXfrGC5rx3ikBH+WT7qgAVjg9WCUJTnk48gKtXRXlbdDFmrJWWbVRW9CMdjIjEAb5CyI261IUAz5gEyBhAn0uW8dB/2z6x1ZtJvhx6nJBZ8M7B0FYDQAiid6v8tgStEpOO0HbUACHfDJTjVEK4aKP1nVmId1Ul+KgBIPNzrZ3y16nenTGnqiOyDlmhZUg33Rj+Hn7OWU++pzADG9o9WLiAk1cDnX9O0Uq7jr2oDyPbWIIbGbdyqSr4+ZhdtwFpM1DPzl9sDbtQjNgDzA3gWF4tigikErwL8uZuI5aKITPjh1QjiUKd6JtN1lHOh2UBntVMI05ORNHCFsXD99Ty07BQXAM9OkcP/VOmoIElZdQFad/fnSpv6rN+XALjg03S+8Z826Zo0p7xXFjcu+3gOtagB+IJXhNCiP8oR+jX1WOSvlx65SHsnhbg2Mh+YCzvzrZftj8Cz3Zsh4G3PS8+LuluXW7CED0M0Gg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jellystat-secret
