hull:
  config:
    specific:
      httpPort: 80
      ingressHost: wallos.joeldollarhide.com

  objects:
    configmap:
    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            wallos-pvc-logos:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: wallos-pvc-logos
            wallos-pvc-db-longhorn:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: wallos-pvc-db-longhorn
          containers:
            app:
              image:
                repository: bellamy/wallos
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
              volumeMounts:
                wallos-pvc-logos:
                  name: wallos-pvc-logos
                  mountPath: /var/www/html/images/uploads/logos
                wallos-pvc-db-longhorn:
                  name: wallos-pvc-db-longhorn
                  mountPath: /var/www/html/db
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 100m
                  memory: 256Mi

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
            protocol: TCP

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Wallos"
          gethomepage.dev/type: "wallos"
          gethomepage.dev/description: "Subscription monitoring"
          gethomepage.dev/group: "Applications"
          gethomepage.dev/icon: "wallos.png"
          gethomepage.dev/weight: "10"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    persistentvolumeclaim:
      wallos-pvc-logos:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 2Gi
      wallos-pvc-db-longhorn:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
