---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: homeassistant-secret
spec:
  encryptedData:
    secrets.yaml: AgBigljiaB6O3/4yr1yKAkC753Rojawje7Vgzq5Swzsfzzw1GQg20Ldew01bMVqbZ90Z8cSuPWokWdDowYCRWr/8s4N9sPAuyHNXh6qq31TYaljPehi1debY9b0urtHiw575laLJ5g+1VunVWmE1aBO2egH+XFJ8+xvrmy/GmI7aMcEHtADsNUSzJjeBNzw8V9Z0uHUtSABFX4MO54e1w//GG/lH/CRx7lCD1YxPQ9sEK24Px2r0Is7M+l42dXMilhVczcyQgt1unA6Mt8lhtQlJHEF7ihDQGtYOGi+2ijk8nWCA6rtbCmTob7mQ11zZH6nzpGcYK4D9bYIbpmGmjx2V5APS7fIf/xEG2XtW8Oevafcyc8BYaZZ7wDj6S+v9/GfSTThjxpxGgP/lTM2d7hasRRBshS+y2pf5f3hT8J+HrkdV44om6KCX3ktbhkVtdFgzxGwf/9PO/6PXcmZ8KQ6n+Lda8eV6PkNiMhO5DgSfHvmY/GZA2ErNQww3c32gUZanze5F706Qmt/txeT/TnWcPZerXk4953QSyaTfNn9OrUNfSCk4qOAGQJuF9zd9NqXlZZZHHyFnjg5C2EeTY/MxziUbeRuZ5VjO1ym0t7sX54WOf0JSmv9H3UxTrhFL58R/NDGO36DGNpUJaC5O5TAwxjcGS3eJmUifNEX/CuMLFWKFkK0Y6oMDxfdkZzjsg97c2xlB
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: homeassistant-secret
