apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: default
spec:
  encryptedData:
    webpassword: AgBSpmnFREN/e4/mmoBjFc+52uP1XQvXasZdxLs7R3nCZipvIcRyUv9vmdPCmMJsQ2PvoLA++0j7q09fCWfbsSlNccgqghVFXBp72OQtGkcww/Nl/U1UrJAauPt985RqwHWuq8kC1r+lD5G86C2Cv2/zMtffyqpzhr2vK0Uc7ag7meICGGZLnIHaVGikywMZf91Yh6+iODpOx/WlS0Q0GvRFAX9gdzuQmfPeuxibfu+MghPjPNwlygQ2k2OMVTdCtEkQ2V5HtFxxM79cZSkARVb/tSCxqoT73Qb5OPOIvcXYTiDsTDqCja2qbMaV2W1hWITtcnm4g5a5uVlh/CybTGIHy4reR1sgCasp7ZCLlw8pvUw+yHl32pCP3hrKSc6qf8lqYTBjJ29YD6g32/d+vOHfut5L04axZMsLTpsd3PYAiN6tfSdE8ZyVYIzDjK4ndXfdCdkoE63voRJGmMXzdK48S8YTdpj+eac6UcwCFXdsONxdC10tSsCYNAbMHiv15gf1g0R6bs+6NBKVieArjOAiSS5CGbImWZ0fs2tvOKKpD3Q5WRzeHJXHYPIEXQEAUchG4LII08KbjeculJBNH1OGRmkoN7cY2hIR/yMQZ5XGx8ZQ5tL/Wr0sraYS/OA7h3Pjuqstv2AtWJa3K+d2JAfYL/pj7Qe1zivtzR4+aBLe5CGhJOJsO/lbWPjgMTnSmF8o287724xd/A==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: default
    type: Opaque

