hull:
  objects:
    configmap:
      app:
        data:
          QBIT_HOST:
            inline: "https://qtorrent.joeldollarhide.com"
          PROWLARR_HOST:
            inline: "https://prowlarr.joeldollarhide.com"
      configs:
        data:
          config.yaml:
            path: files/config.yaml

    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            configs:
              active: configMap
              configMap:
                name: configs
          containers:
            app:
              image:
                repository: ghcr.io/mrmarble/yoink
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              envFrom:
                app:
                  configMapRef:
                    name: app
                    optional: false
                sealed:
                  secretRef:
                    staticName: true
                    name: yoink-secret
              volumeMounts:
                configs:
                  name: configs
                  mountPath: /config.yaml
                  subPath: config.yaml
                  readOnly: true
