# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

sonarr:
  main_sonarr:
    base_url: !env_var SONARR_BASE_URL
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: series
    custom_formats:
      - trash_ids:
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD Atmos
          - 3fbafa924f361e66fbc6187af82dfa85 # 5.1 Sorround

          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras

          - cddfb4e32db826151d97352b8e37c648 # x264
          - e6258996055b9fbab7e9cb2f75819294 # Web Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # Web Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # Web Tier 03

          - e0014372773c8f0e1bef8824f00c7dc4 # Anime Web Tier 01
          - 19180499de5ef2b84b6ec59aae444696 # Anime Web Tier 02
          - c27f2ae6a4e82373b0f1da094e2489ad # Anime Web Tier 03
          - 4fd5528a3a8024e6b49f9c67053ea5f3 # Anime Web Tier 04
          - 29c2a13d091144f63307e4a8ce963a39 # Anime Web Tier 04
          - dc262f88d74c651b12e9d90b39f6c753 # Anime Web Tier 04

        assign_scores_to:
          - name: HD-1080p
          - name: Any

radarr:
  main_radarr:
    base_url: !env_var RADARR_BASE_URL
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: movie
      preferred_ratio: 0.5
    custom_formats:
      - trash_ids:
          - 77ff61788dfe1097194fd8743d7b4524 # 5.1 Surround
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos

          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          # HQ Release Groups
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03

          - 2899d84dc9372de3408e6d8cc18e9666 # x264

          # Anime Release Groups
          - 8167cffba4febfb9a6988ef24f274e7e # Anime Web Tier 01
          - 8526c54e36b4962d340fce52ef030e76 # Anime Web Tier 02
          - de41e72708d2c856fa261094c85e965d # Anime Web Tier 03
          - 9edaeee9ea3bcd585da9b7c0ac3fc54f # Anime Web Tier 04
          - 22d953bbe897857b517928f3652b8dd3 # Anime Web Tier 05
          - a786fbc0eae05afe3bb51aee3c83a9d4 # Anime Web Tier 06
        assign_scores_to:
          - name: HD-1080p
          - name: Any
