# yaml-language-server: $schema=https://raw.githubusercontent.com/vidispine/hull/refs/heads/main/hull/values.schema.json

hull:
  config:
    specific:
      httpPort: 5055
      ingressHost: jellyseerr.joeldollarhide.com

  objects:
    configmap:
      app:
        data:
          TZ:
            inline: "America/New_York"

    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            jellyseerr-pvc-config:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: jellyseerr-pvc-config
          containers:
            app:
              image:
                repository: fallenbagel/jellyseerr
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
              volumeMounts:
                jellyseerr-pvc-config:
                  name: jellyseerr-pvc-config
                  mountPath: /app/config
              envFrom:
                app:
                  configMapRef:
                    name: app
                    optional: false
              resources:
                requests:
                  cpu: 200m
                  memory: 1500Mi
                limits:
                  cpu: 200m
                  memory: 1500Mi

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
            protocol: TCP

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Jellyseerr"
          gethomepage.dev/description: "Media request platform"
          gethomepage.dev/group: "Streaming"
          gethomepage.dev/icon: "jellyseerr"
          gethomepage.dev/weight: "1"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    persistentvolumeclaim:
      jellyseerr-pvc-config:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 5Gi

