# yaml-language-server: $schema=https://raw.githubusercontent.com/vidispine/hull/refs/heads/main/hull/values.schema.json

hull:
  config:
    specific:
      httpPort: 5055
      oldIngressHost: &oldIngressHost jellyseerr.joeldollarhide.com
      ingressHost: &ingressHost seerr.joeldollarhide.com

  objects:
    serviceaccount:
      default:
        enabled: false

    customresource:
      redirect-seer:
        apiVersion: traefik.io/v1alpha1
        kind: Middleware
        spec:
          redirectRegex:
            regex: ^https?://jellyseerr(.*)
            replacement: https://seerr${1}
            permanent: true

      app:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        spec:
          instances: 1

          monitoring:
            enablePodMonitor: true

          managed:
            services:
              disabledDefaultServices: ["ro", "r"]

          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 100m
              memory: 1Gi

          storage:
            storageClass: nfs
            size: 5Gi

    persistentvolumeclaim:
      jellyseerr-pvc-config:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 5Gi


seerr-chart:
  config:
    persistence:
      existingClaim: jellyseerr-pvc-config

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-jellyseerr-jellyseer-redirect-seer@kubernetescrd

      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Seerr"
      gethomepage.dev/description: "Media request platform"
      gethomepage.dev/group: "Streaming"
      gethomepage.dev/icon: "seerr"
      gethomepage.dev/weight: "1"
    hosts:
      - host: *oldIngressHost
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: *ingressHost
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: jellyseerr-tls
        hosts:
          - *oldIngressHost
          - *ingressHost

  extraEnv:
    - name: TZ
      value: "America/New_York"
    - name: DB_TYPE
      value: postgres
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: jellyseerr-jellyseer-app-app
          key: host
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: jellyseerr-jellyseer-app-app
          key: user
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: jellyseerr-jellyseer-app-app
          key: password
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: jellyseerr-jellyseer-app-app
          key: dbname

  resources:
    requests:
      cpu: 200m
      memory: 1500Mi
    limits:
      cpu: 200m
      memory: 1500Mi
