total_freeleech_size: "300GB" # Max space to use for downloads. If 0, no limit is applied
category: "Movies" # Category to use for downloads.
paused: false
indexers: # List of indexers to use. Filters out any indexers not in this list
  - id: 15 # Digital Core
    max_seeders: 0 # Maximum number of seeders to allow. 0 = no limit
    max_size: "20GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
