total_freeleech_size: "200GB" # Max space to use for downloads. If 0, no limit is applied
category: "FreeLeech" # Category to use for downloads.
paused: false
indexers: # List of indexers to use. Filters out any indexers not in this list
  - id: 9 # Nyaa.si
    max_seeders: 10 # Maximum number of seeders to allow. 0 = no limit
    max_size: "50GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
  - id: 10 # Pirate Bay
    max_seeders: 10 # Maximum number of seeders to allow. 0 = no limit
    max_size: "50GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
  - id: 11 # RARBG
    max_seeders: 10 # Maximum number of seeders to allow. 0 = no limit
    max_size: "50GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
  - id: 12 # Tokyo Toshokan
    max_seeders: 10 # Maximum number of seeders to allow. 0 = no limit
    max_size: "50GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
