---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: minecraft-secret
spec:
  encryptedData:
    FabricProxy-Lite.toml: AgBw6T6CElFTK78ZovJZ+HJ2ULerpKZPfjBxBqllCkSuAsM7PG60vnhCsM8LXuDy0sHOEAJEnlpj8VSZ5O9f6RWI+G8a4dLwQxFgnMqJcm4Xw+6fRiwWmSqx9Gx01wVnSJs4NZTuKC5pCIFS/qfV0UV3WEozwlO1kvKrJuTQokXr9KKuMsTqLVkN3zNMiHj9IZ/RnNEhI6HZZH6VO+NbBveuB2YTvceAz+H2tGyDis0hNBN2WRKPWXNvG2RwllUVTJpIeZJFjwuJ3726X9gZE8MdbUEpSle48++hzSQTHHSu3kUUWq7IsOyuTn+CnbZB0cPjS+X2P8xhZtdtD58TbHNn8uVcSh3NNUtdFY0onr+0oK4aJwEyAUxpsP9nsPjrdmE+tIrMWm1eb9h21eP+05d1Us97hdeB54Ge2vGVBYOttJKozvax7ONm5LVx1J2+Ky97926v242FZc/sK/e0ZrPa1nbxGhreINjxI7w7DwN/azhEPwPHa7z/aPwDFGevkP01aXsUZIEnQQCN/r8VZloLq7YAFSELcGL6UOB9Lxkv7356iM99OEQ91LasRiX5MRhfH1t3b69bPLadd06w0AAGB0Stu0CeezgsvbYAopA4nA5lC5UJqiou3ncx73ZidZ6nYlhK8I2ZPg7WUshbEN2tdsRYa32itVq3ihLQF5bYYfhkteB419yP59rKyBAD0HtGQmytcwDAmfw5g2xPbk+1sAAEQn5bCH0h9Kiv4ONR2illxylft2Vqx6PQ8mzvOBl2JEojUAGz6viX2yeq+52bk37D6XGaOtfOno+LYmFcWCvKcuEluohVsOB5mcbtJQ2WaVnSeu2rBopvysvXFr3nVqo0EK5csQmluVUltowZetQWVKrs0nPt21NNDt+m/0oalrWQZ3WnQKqH4+dkDMQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: minecraft-secret
