config:
  # Name of the node in proxmox where the VM template lives
  infrastructure:template-node-name: baroque
  # ID of the VM template in proxmox
  infrastructure:template-vm-id: "9001"
  # IP of the network gateway
  infrastructure:gateway-ip: 10.0.0.1
  # Password for the user provided by proxmoxve-username
  # to sign in to the proxmox console
  infrastructure:proxmoxve-password:
    secure: AAABABoFXzibuW0mSHplzMkvcebVgIgltw2xnCKtjd6qaZiRTqMCdw==
  # User used to sign into the proxmox console
  infrastructure:proxmoxve-username:
    secure: AAABANN4J8TxUw0DvhUVUisDw37JYoNfbRdu8qpMl6sqr8ucWdVNtA==
  infrastructure:vm-user-name: jdollar
  infrastructure:vm-user-password:
    secure: AAABAGSkQ2e3BIXpjTaYhrut0NV2UQsnSs/SLuA3RsccgPPrb7qMBQ==
  proxmoxve:endpoint: https://10.0.0.87:8006
  proxmoxve:insecure: "true"
  hertzner:api-token:
    secure: AAABAGCisoBQXE3PREtVlOhyuWSI7U0luu0GLpDKF9DfQyW36/Rg3LIoYY1XnmevyfKdtS0QenkrGEfH3UnJmK5kNzNFS1IxNqc9Uu8h5dEve44pdEEUXpwzZqAl2o7s
  hertzner:storage-boxes:
    backups:
      delete-protection: true
      features:
        reachable-externally: true
        samba: false
        ssh: true
        webdav: false
        zfs: false
      location: fsn1
      snapshot-plan:
        day-of-week: 3
        hour: 18
        max: 10
        minute: 16
      type: bx11
      subaccounts:
        restic:
          password:
            secure: AAABANuqROGmMFt44i7aGIxejobayrZl0qVv8Ndcelse3hM3fno2xjEz81V7rQ==
  infrastructure:templates:
    debian-12:
      datastore-id: local-lvm
      node-name: baroque
      operating-system-type: l26
      vm-id: 9001
  infrastructure:vms:
    daisy:
      cpu-cores: 3
      dedicated-memory: 8192
      disk-datastore-id: local-lvm
      disk-size: 250
      ip: 10.0.0.7/24
      mac-address: BA:3D:60:5F:BD:E4
      machine: pc
      node-name: antebellum
      template: debian-12
    lily:
      cpu-cores: 3
      dedicated-memory: 16384
      disk-datastore-id: local-lvm
      disk-size: 150
      ip: 10.0.0.93/24
      mac-address: 4A:8A:75:94:90:2F
      machine: pc
      node-name: pve-gardenesque
      template: debian-12
    sage:
      cpu-cores: 3
      dedicated-memory: 16384
      disk-datastore-id: local-lvm
      disk-size: 250
      ip: 10.0.0.94/24
      mac-address: 2E:39:07:EF:C9:68
      machine: pc
      node-name: pve-gardenesque
      template: debian-12
      vga-type: std
    tulip:
      cpu-cores: 4
      dedicated-memory: 20480
      disk-datastore-id: ssd
      disk-size: 300
      ip: 10.0.0.92/24
      mac-address: 56:94:8F:C6:0B:5E
      machine: pc
      node-name: baroque
      template: debian-12
    violet:
      cpu-cores: 6
      dedicated-memory: 8192
      disk-datastore-id: ssd
      disk-size: 250
      ip: 10.0.0.90/24
      mac-address: 56:41:94:7B:8E:38
      machine: pc
      node-name: baroque
      template: debian-12
      vga-type: std
  hertzner:vm-password:
    secure: AAABAAR9h0ijNy5MTbsCIiMPVhXJgV5w/0Ig60C9AcBhP252pJwgo6xfOQHD5g==
