---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: recyclarr-secret
spec:
  encryptedData:
    RADARR_API_KEY: AgBJgOmjoJMfROLqvN2+Jv1O5fLzMktDwpGj5IW/n9N+dZ5EAfS+6thk+uKrcRs1p4xVywW3EJZB5b8Il2K/fSUUNTucs2rc8qwUIt/E1L5G55wCJCbh+KFGOpmUUotQzJv3Huu+hN5Gzhtvl9Clz5Ea3ZPdaC+ki+cBsPIHZLVc6zMvovCzm1YmOW2LuxguntNKMKvx2WK+0DBKJ7YcipUnGlP4lHoKA4ldKP+UNoa7QAaOh146uelvRyxa3JNd/8J2Ce8OPxFPyq9I92mAChbrEDFJ/9kt1ZIythp8E+Lew52B36jIyapx7XKxPBYPRVt7Zzud0jbZQJYXMy3Um1mvspPW/xRHKv+Y++3//g3QjeEJyGDoqW0R4a63U3o2bORMR4n0cRnsXGiZoZEN+9vULfS1PTLrkDZk7MNvcUJs7J+6caj8RcMskYiXCCB1PZiYZGoB9mIpNQvid5xA4gBBtUdajKwgQZQhkSLHW86pR3ocdfmG5e4Czq+UMQLKK/J0M7lXNfGLVUBDCQqKirTUb49M3GYFcxvmBk4kw/lTt/jYaG3SBm5RzBJVl15yIYJH+40+a4HNrWotOmnVWxI26EHlgrgRlIMdZxTGmOxsDGOJO68iE4KwlD5hbuphE1YNW09sLkyCXnGzQuWNq8tiN7oOGj4sILol+ZlUwFVC5FFgvilX2HwFqI+PwhDKDlTs3+agFYGKT+MVg6vYWPr5hJfAPfHrQQMugyvHTZQhtA==
    SONARR_API_KEY: AgBfoiPnpdMN9LNhe2QA8ZJxEV3PctJfjSvwEh87RnGSSce1LA9ZxbdMj1HW91LxxX3A24dYxUu5t05eC+BFDs+4AhOsilf84Wrh/NWkopjnqbc2IR7tH58IxgdXhda92kJg0kYwglZsDfOSAYrfH9rbgBffBjNyjps1jaxZumQTn3kxFwMEWQtk0kcySd+i3Aq6a13Yq1yl+2HOj6TzKKnCBVhJZ+alsKSbJqWrzp6bebz6+aanRRbm9hj8clQMnYUWkHTXXRYk4kZ/EJ0GBh+LfEvwKOfdBjEfIwhfOKf/X31WQlwV6elQ04/UMdLpWbohuXgHWNu3PH/8D6E14GtvxT3DLCFr0u6w7LKOem2Jxa1wYj6BTUN93Kd454ZgTylMQdcpK76GDiCjqI2nqfgRJOZcnL48HXeC6OMVEaIbq9k+Y4R3v3b3JLZpcNs4knybGaDsk1o8j1R9Cz8mS6y/N0TSrIsR/eZVprCVHgf45kAQlReIY62BeWoQRFZ8M9pauCobaP/r4v8f3znERHCd8S6NctXR0V4ePCLLOzXniwPcfxVzGiRatH50aTXfWEuhzPR/15NUAOKtgL10udD0bH9mYh6ad6+VsOQLddLkrS1rl67I0n0lLMnTTwT5g74M36QO97uVlRaAa7NNTkqcWMPatFG82vo9OQaMZBEC7OZqlMUcM84mKxkgH6WU4n1+bFX827cy3QuNNoutI717PAQ+W7RnndWcl5S7qB97Ag==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: recyclarr-secret
