---
- name: Install the latest version of keepalived
  become: true
  ansible.builtin.package:
    name:
      - keepalived
    state: latest

- name: Ensure group "keepalived_script" exists
  become: true
  ansible.builtin.group:
    name: keepalived_script
    state: present

- name: Add the user 'keepalived_script'
  become: true
  ansible.builtin.user:
    name: keepalived_script
    create_home: false
    shell: /sbin/nologin
    groups: keepalived_script

- name: ensures keepalived config dirs exists
  become: true
  file:
    path: "/etc/keepalived/{{ item.name }}"
    state: directory
    group: "{{ item.group }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop:
    - { name: "conf.d", owner: "root", group: "root", mode: "0755" }
    - { name: "scripts.d", owner: "keepalived_script", group: "keepalived_script", mode: "0755" }

- name: Copy base config file
  become: true
  copy:
    src: files/keepalived.conf
    dest: "/etc/keepalived/"

