---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: searxng-secret
spec:
  encryptedData:
    SEARXNG_SECRET: AgCUp5CuW3nSjvTxLi3A7LBc+YMP+Jg38uVXCoL8sxeFW17s4EOTRZ9PPkTdgt/DfmNjWKeLRB4nnq+MhZYL/LCgHP/ztWjMTTryQ7X1Q3DPO371ouaaLF4g/zGsz72sh414Bx8sNrV2NVGUxTwxzYumrdNnrI7iwgvd0vEtbKm1wDVzkrSgTj2wjBYqO6OyWcV3TWhcMzGZEgpQ8iCSPP7knNHzeYj4ADF7hkbO8hU41w5pNqqeNiyuzzrD3t+Ssn4G8SjIHcaq9Y+MmD32Pxaw5Xeva08VFpC2g1QRyIJ2nsiLrrjlTQTeAyq08wmZOv9/vRJ7nMn7y8BwSXlvW1jFgBIoQsX/e6Xe4YWoTMIONM9Kvw2hvU0Fi74IUp9I4DCu+wbyZjEegN1WiNl37cllUjMnZ9+/vWtXh8YibAy9RucPrxC7+ur8r6FdTjrRGTkE+jwc2U+tDnfUd95sEZzjYSFJXAIT5SwWcXEqDk7oE3PZmsovyZI1WH7HBtoHiKjJcX/SfIMX3D0mXDsL0qbGg/KnSIsvt9Y8osLzAFgxLMpPQDenFtgK/BbzBek8dnTRsdSbH8PmU3Rwu14Qhthjm6LtoJ+IoZ883NOkR1tzv4I/a7NdrznInmqw4Lf93aYYjY2BbslfFAz2qVpdS4ShRgOt1RYm5exf6xyA1AXJtc8oplaRnxEYA/+Sl7chiyuvcYH4N/3ThZyFDJV6PA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: searxng-secret
