hull:
  config:
    specific:
      replicas: 0
      httpPort: 8409
      ingressHost: ersatztv.joeldollarhide.com

  objects:
    configmap:
      app:
        data:
          TZ:
            inline: "America/New_York"

    deployment:
      app:
        replicas: _HT*hull.config.specific.replicas 
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            jellyfin-pvc-media:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: jellyfin-pvc-media
            ersatztv-pvc-config:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: ersatztv-pvc-config
          containers:
            app:
              image:
                repository: jasongdove/ersatztv
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
              volumeMounts:
                ersatztv-pvc-config:
                  name: ersatztv-pvc-config
                  mountPath: /root/.local/share/ersatztv
                jellyfin-pvc-media:
                  name: jellyfin-pvc-media
                  mountPath: /data
              envFrom:
                app:
                  configMapRef:
                    name: app
                    optional: false
              resources:
                requests:
                  cpu: 100m
                  memory: 2500Mi
                limits:
                  cpu: 400m
                  memory: 2500Mi

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
            protocol: TCP

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Ersatztv"
          gethomepage.dev/type: "ersatztv"
          gethomepage.dev/description: "TV Channel Setup"
          gethomepage.dev/group: "Streaming"
          gethomepage.dev/icon: "ersatztv.png"
          gethomepage.dev/weight: "10"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    persistentvolumeclaim:
      ersatztv-pvc-config:
        staticName: true
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
