nginx:
  staticSitePVC: "jdollarblog-staging-jdollarblog-pvc-public"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    hostname: staging.joeldollarhide.com
    tls: true

