# yaml-language-server: $schema=https://raw.githubusercontent.com/vidispine/hull/refs/heads/main/hull/values.schema.json

hull:
  config:
    specific:
      httpPort: 9696
      ingressHost: prowlarr.joeldollarhide.com

  objects:
    configmap:
      app:
        data:
          TZ:
            inline: "America/New_York"
          UMASK:
            inline: "002"
          PUID:
            inline: "1000"
          PGID:
            inline: "1000"

    deployment:
      app:
        replicas: 1
        strategy:
          type: Recreate
        templateLabels:
          app.kubernetes.io/type: app
        pod:
          volumes:
            prowlarr-pvc-config-longhorn:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: prowlarr-pvc-config-longhorn
            jellyfin-pvc-media:
              active: persistentVolumeClaim
              persistentVolumeClaim:
                staticName: true
                claimName: jellyfin-pvc-media
          containers:
            prowlarr:
              image:
                repository: ghcr.io/hotio/prowlarr
                pullPolicy: IfNotPresent
                tag: _HT**Chart.appVersion
              ports:
                http:
                  containerPort: _HT*hull.config.specific.httpPort
                  protocol: TCP
              volumeMounts:
                prowlarr-pvc-config-longhorn:
                  name: prowlarr-pvc-config-longhorn
                  mountPath: /config
                jellyfin-pvc-media:
                  name: jellyfin-pvc-media
                  mountPath: /data
              envFrom:
                prowlarr:
                  configMapRef:
                    name: app
                    optional: false
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  cpu: 100m
                  memory: 512Mi

    service:
      app:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: _HT*hull.config.specific.httpPort
            protocol: TCP

    ingress:
      app:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Prowlarr"
          gethomepage.dev/description: "Download index monitoring"
          gethomepage.dev/group: "Streaming"
          gethomepage.dev/icon: "prowlarr"
          gethomepage.dev/weight: "23"
        rules:
          app:
            host: _HT*hull.config.specific.ingressHost
            http:
              paths:
                root:
                  path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: app
                      port:
                        name: http
        tls:
          app:
            enabled: true
            secretName: tls
            hosts:
              - _HT!
                [
                {{ (index . "$").Values.hull.config.specific.ingressHost }}
                ]

    persistentvolumeclaim:
      prowlarr-pvc-config-longhorn:
        staticName: true
        labels:
          "recurring-job.longhorn.io/snapshot-cleanup": "enabled"
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
